name: NuGet Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --configuration Release --no-restore

      - name: Run tests
        run: dotnet test --no-restore --verbosity normal

      - name: Get current version
        id: get_version
        run: |
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          echo "::set-output name=VERSION::$VERSION"

      - name: Calculate next version
        id: next_version
        run: |
          CURRENT_VERSION=${{ steps.get_version.outputs.VERSION }}
          IFS='.' read -r -a VERSION_PARTS <<< "$CURRENT_VERSION"
          MAJOR=${VERSION_PARTS[0]}
          MINOR=${VERSION_PARTS[1]}
          PATCH=${VERSION_PARTS[2]}
          PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$PATCH"
          echo "::set-output name=NEW_VERSION::$NEW_VERSION"

      - name: Set version
        run: echo "VERSION=${{ steps.next_version.outputs.NEW_VERSION }}" > version.txt

      - name: Pack project
        run: dotnet pack --configuration Release /p:PackageVersion=${{ steps.next_version.outputs.NEW_VERSION }} --no-restore

      - name: Create Git tag
        run: git tag ${{ steps.next_version.outputs.NEW_VERSION }}

      - name: Push tags
        run: git push origin --tags --follow-tags -u Belinazzi:${{ secrets.GH_TOKEN }}

      - name: Publish to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push '**/*.nupkg' --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

      - name: Publish to GitHub Packages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: dotnet nuget push '**/*.nupkg' --api-key $GH_TOKEN --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
